#!/bin/bash
set -x -e

PREFIX=imikushin

cd $(dirname $0)/..

for i in scripts/dockerimages/[0-9]*; do
    tag=`echo ${i} | awk 'sub(/^.+\/[0-9]+-/, "")'`
    echo Building ${tag}
    docker build -t ${PREFIX}/${tag} -f ${i} .
done
